apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lotservice
  name: lotservice-no7ex0
spec:
  selector:
    matchLabels:
      app: lotservice
  replicas: 1
  template:
    metadata:
      labels: 
        app: lotservice
    spec:
      containers:
        - name: lottery-service-hcigop
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/jhlinux/lottery_service:v1.0
      serviceAccount: default
      imagePullSecrets:
        - name: docker-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: lotservice
spec:
  selector: 
    app: lotservice
  sessionAffinity: ClientIP
  ports:
    - name: grpc-9090
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
