kind: ConfigMap
apiVersion: v1
metadata:
  name: application
  labels:
    app: application
  annotations: {}
data:
  application.yml: >-
    server:
      port: 8090
    spring:
      application:
        name: lottery-web
      datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql
        url: jdbc:p6spy:h2:mem:test
        username: root
        password: test
    grpc:
      client:
        lottery-service:
          address: 'static://lotservice:9090'
          enableKeepAlive: true
          keepAliveWithoutCalls: true
          negotiationType: plaintext

    knife4j:
      basic:
        enable: true
        username: sinodata
        password: 123

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: https://registry.cn-hangzhou.aliyuncs.com 
type: kubernetes.io/basic-auth
stringData:
  username: "17751776505"
  password: "ZJ6505zj"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lotweb
  name: lotweb-no7ex0
spec:
  selector:
    matchLabels:
      app: lotweb
  replicas: 1
  template:
    metadata:
      labels: 
        app: lotweb
    spec:
      volumes:
        - name: application-config
          configMap:
            name: application
      containers:
        - name: lottery-web-hcigop
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/jhlinux/lottery_web:v3
          volumeMounts:
            - name: application-config
              mountPath: /config
      serviceAccount: default
      imagePullSecrets:
        - name: docker-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: lotweb
spec:
  selector: 
    app: lotweb 
  sessionAffinity: ClientIP
  ports:
    - name: http-8090
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
