spring:
  application:
    name: lottery-service
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test
#    # mysql 连接配置
#    # driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#    url:  jdbc:p6spy:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: william
#    initialize: true
#    initialization-mode: always


grpc:
  server:
    port: 9090
