DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	phone VARCHAR(50) NULL DEFAULT NULL COMMENT '电话',
	address VARCHAR(50) NULL DEFAULT NULL COMMENT '地址',
	PRIMARY KEY (id)
);